# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61fc540f844a885d11a84e0e647fa9b564dbab1cd1f5832a0080429fae7c089d5ef79abecd0845f97397f232498163034695ef831251ecd1796a667748a5c29b

test:
  secret_key_base: ca0aa69aeb7d200c62c6db599a2b329d7ea16b1b5f5049b7a201f1288c2a46fe3a3214a32f8485ae807197e33928e5666f884b9e1328a18c2b2293f041cb6c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
